// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOzB7DYP0WkftR0oyBRd0oZvtNENqOnKo',
    appId: '1:408094509915:web:16c2cd00f68d99499ce87e',
    messagingSenderId: '408094509915',
    projectId: 'ss-home-a7ec2',
    authDomain: 'ss-home-a7ec2.firebaseapp.com',
    storageBucket: 'ss-home-a7ec2.firebasestorage.app',
    measurementId: 'G-57031DY74L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFkMSRRgoWK3EISAf5CuWKUMOl0r_QLBs',
    appId: '1:408094509915:android:115db515c502a1879ce87e',
    messagingSenderId: '408094509915',
    projectId: 'ss-home-a7ec2',
    storageBucket: 'ss-home-a7ec2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcJaqb4HXqZyE3yHTfgeKBqFxsxeHXYi4',
    appId: '1:408094509915:ios:629462974a7745639ce87e',
    messagingSenderId: '408094509915',
    projectId: 'ss-home-a7ec2',
    storageBucket: 'ss-home-a7ec2.firebasestorage.app',
    iosBundleId: 'com.example.ssHome',
  );
}
